version: '3.9'

services:
  app:
    container_name: app
    image: hyperf/hyperf:8.0-alpine-v3.13-swoole
    working_dir: /app
    entrypoint: ["php", "bin/hyperf.php", "server:watch"]
    volumes:
      - ./:/app
    ports:
      - 9501:9501
    depends_on:
      - mariadb
      - redis

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "hyperf"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  mariadb:
